In [1]:
import numpy as np

In [3]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

# numpy ile nokta doğru düzlem ve uzay


In [8]:
skaler = np.array(90) #sakaler büyüklük
print(skaler)

90


In [9]:
vektor = np.array([1,2,3,4,5,6,7]) # vektörel büyüklük
print(vektor)

[1 2 3 4 5 6 7]


In [10]:
matris = np.array([[1,2,3,4,5],[6,7,8,9,10]]) #matrix büyüklük 2 boyutlu
print(matris)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
tensor = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) # tensor büyüklük 3 boyutlu ve fazlası
print(tensor)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# index ve slice

In [12]:
vektor=np.array([0,2,4,5,6,7,8,15])

In [13]:
vektor[0]

0

In [15]:
vektor[-1] #sondan 1. elemanı gösterir

15

In [14]:
vektor[1:3] # 1 den 3. elamana  kadar olanları ekrana yazdırır 3. eleman dahil değil

array([2, 4])

In [16]:
vektor[:5] # baştan 5. elamana kaadr olanları gösterir 5. elaman dahil değil

array([0, 2, 4, 5, 6])

In [17]:
vektor[2:6:2] # 2.elemandan 6. elamana kadar 6. elaman dahil değil ikişer ikişer artış şeklinde ekrana yazdır

array([4, 6])

# size , shape , dtype , ndim

In [19]:
vektor=np.array([1,2,3,4,5,6])
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
print(vektor)

[1 2 3 4 5 6]


In [21]:
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
vektor.size # size kaç elemandan oluştuğunu gösterir

6

In [23]:
matris.size

9

In [24]:
vektor.shape

(6,)

In [25]:
matris.shape #  shape (şekli hakkında bilgi verir)

(3, 3)

In [26]:
vektor.ndim # ndim kaç boyutlu olduğunu gösterir

1

In [27]:
matris.ndim

2

In [28]:
vektor.dtype

dtype('int64')

In [29]:
matris.dtype

dtype('int64')

# numpy veri tipi değiştirme

In [31]:
numbers=np.array([1,2,3,4,5,6])

In [32]:
numbers.dtype

dtype('int64')

In [33]:
numbers=np.array([1,2,3,4,5.0,6])

In [34]:
numbers.dtype

dtype('float64')

In [35]:
numbers  = numbers.astype("int8")

In [37]:
numbers = np.array([1,2,3,4,5,6],dtype="int8")
numbers.dtype

dtype('int8')

In [39]:
tarih= np.array([2024-12-22])

In [43]:
tarih.dtype

dtype('int64')

In [44]:
tarih=tarih.astype("datetime64")
tarih.dtype

dtype('<M8')

# matrislerde slice


In [46]:
matris=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
matris[0]

array([1, 2, 3, 4])

In [48]:
matris[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
matris[0,:2] # 0. satırda 2.elamana kadar olan sayılar(2. eleman dahil değil)

array([1, 2])

In [50]:
matris[0:4,0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [52]:
matris[2:4,1:3]

array([[10, 11],
       [14, 15]])

# random matris oluşturma

In [53]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [54]:
np.random.randint(0,10,(4,4)) # 0 ile 10 sayıları arasında ( 10 dahil değil) 4*4 lük matris oluşturma

array([[3, 7, 7, 4],
       [6, 9, 4, 0],
       [7, 6, 3, 6],
       [2, 0, 5, 7]])

# arange ile vektör oluşturma

In [56]:
numbers =np.arange(1000000)
numbers

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [57]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [58]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# linspace() ile vektör oluşturma

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [61]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [64]:
numbers=np.linspace(0,20,10) # burda son eleman olan 20 dahil 0 ile 20 aralığnı 10 eşit parçaya böler
numbers

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [65]:
numbers[5]-numbers[4]

2.2222222222222214

# numpy yeniden boyutlandırma reshape() metodu

In [66]:
m1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
m1.shape

(3, 4)

In [68]:
m1.size

12

In [69]:
m1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [70]:
m1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [73]:
m1.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [78]:
np.linspace(0,20,30).reshape(2,10) # reshape için yazdığımız değerlerin çarpımı eleman saysına eşit olmalı mesala (2,10) yazarsak hata alırız (cannot reshape array of size 30 into shape (2,10))

ValueError: cannot reshape array of size 30 into shape (2,10)

In [79]:
np.linspace(0,20,30).reshape(5,6)

array([[ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
         3.44827586],
       [ 4.13793103,  4.82758621,  5.51724138,  6.20689655,  6.89655172,
         7.5862069 ],
       [ 8.27586207,  8.96551724,  9.65517241, 10.34482759, 11.03448276,
        11.72413793],
       [12.4137931 , 13.10344828, 13.79310345, 14.48275862, 15.17241379,
        15.86206897],
       [16.55172414, 17.24137931, 17.93103448, 18.62068966, 19.31034483,
        20.        ]])

# copy() ve view() metodları

In [81]:
matris=np.random.randint(0,6,(4,4))
matris

array([[2, 5, 3, 3],
       [1, 0, 1, 1],
       [5, 3, 3, 1],
       [4, 1, 2, 4]])

In [84]:
matris2=matris.view()
matris2

array([[2, 5, 3, 3],
       [1, 0, 1, 1],
       [5, 3, 3, 1],
       [4, 1, 2, 4]])

In [86]:
matris2[0]=[9,9,9,9]
matris2

array([[9, 9, 9, 9],
       [1, 0, 1, 1],
       [5, 3, 3, 1],
       [4, 1, 2, 4]])

In [87]:
matris

array([[9, 9, 9, 9],
       [1, 0, 1, 1],
       [5, 3, 3, 1],
       [4, 1, 2, 4]])

In [88]:
matris3=np.random.randint(0,5,(4,4))
matris3

array([[4, 0, 1, 4],
       [1, 4, 4, 3],
       [4, 4, 4, 2],
       [4, 1, 3, 1]])

In [89]:
matris4=matris3.copy()

In [90]:
matris4

array([[4, 0, 1, 4],
       [1, 4, 4, 3],
       [4, 4, 4, 2],
       [4, 1, 3, 1]])

In [92]:
matris4[0]=[4,4,4,4]
matris4

array([[4, 4, 4, 4],
       [1, 4, 4, 3],
       [4, 4, 4, 2],
       [4, 1, 3, 1]])

In [93]:
matris3

array([[4, 0, 1, 4],
       [1, 4, 4, 3],
       [4, 4, 4, 2],
       [4, 1, 3, 1]])

# ones(),zeros() ve full() matris oluşturma metotları

In [94]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [95]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [99]:
np.ones(shape=(4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [100]:
np.full((5,6),20)

array([[20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

# numpy eye() , diag() , identity() metotları

In [104]:
import numpy as np

In [107]:
np.identity(6) # köşegenleri 1 olan 0 matris oluşturma

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [109]:
np.eye(6,k=2) # köşegenleri k birim öteler

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [111]:
np.diag([1,2,3,2,1])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [112]:
r= np.random.randint(0,3,(5,5))
r

array([[1, 2, 2, 0, 0],
       [2, 1, 0, 0, 1],
       [0, 2, 0, 2, 1],
       [2, 2, 2, 2, 0],
       [1, 2, 0, 0, 2]])

In [113]:
np.diag(r)

array([1, 1, 0, 2, 2])

In [114]:
np.diag(np.diag(r)) # r matrisin köşegeni ile yeni matris oluşturdu

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 2]])

# matris ve vektörlerde çarpma toplama çıkarma bölme

In [120]:
m1 = np.ones((5,5))
m2=np.full((5,5),19)

In [121]:
m1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [122]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [123]:
m1*4

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [124]:
m1=m1.astype("int16")

In [125]:
m1*4

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]], dtype=int16)

In [126]:
m2%3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [146]:
m3=np.full((5,6),2)
m3

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [129]:
m2+m3

ValueError: operands could not be broadcast together with shapes (5,5) (5,6) 

In [150]:
m3=m3.reshape(30)[:25].reshape(5,5).view()

In [151]:
m3

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [152]:
m2+m3

array([[21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21]])

In [154]:
m1[0]=m1[0]*3
m1

array([[9, 9, 9, 9, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [156]:
m5 = np.arange(5).reshape((5,1))
m5

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [157]:
m1*m5

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [158]:
m6=m1+m5
m6

array([[9, 9, 9, 9, 9],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [159]:
m6*np.diag(m6)

array([[81, 18, 27, 36, 45],
       [18,  4,  6,  8, 10],
       [27,  6,  9, 12, 15],
       [36,  8, 12, 16, 20],
       [45, 10, 15, 20, 25]])

# numpy ile mantıksal operatörler ve filtreleme

In [161]:
matris= np.random.randint(0,10,(5,5))
matris

array([[6, 2, 8, 1, 9],
       [9, 6, 1, 5, 5],
       [0, 4, 3, 4, 0],
       [5, 4, 5, 0, 5],
       [7, 9, 8, 9, 7]])

In [162]:
matris>5

array([[ True, False,  True, False,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [163]:
matris[matris>5]

array([6, 8, 9, 9, 6, 7, 9, 8, 9, 7])

In [164]:
matris[matris == 4].size

3

In [167]:
matris[matris%2==0]

array([6, 2, 8, 6, 0, 4, 4, 0, 4, 0, 8])

In [168]:
matris[matris%2==0].size

11

In [170]:
sifir=matris!=0
cift=matris %2==0
bir=matris==1

In [171]:
matris[cift&sifir]

array([6, 2, 8, 6, 4, 4, 4, 8])

In [172]:
matris[cift | bir]

array([6, 2, 8, 1, 6, 1, 0, 4, 4, 0, 4, 0, 8])

In [173]:
matris[(cift & sifir) | bir]

array([6, 2, 8, 1, 6, 1, 4, 4, 4, 8])